export const Overview = 'overview'
export const OverviewExchangeData = 'overviewExchangeData'
export const OverviewUnionData = 'overviewUnionData'
export const OverviewRedBlackList = 'overviewRedBlackList'
// export const OverviewRedBlackList = 'overviewRedBlackList'

export const Union = 'union'
export const Public = 'publicState'
export const Summary = 'summary'
export const Map = 'map'
