export const Overview = 'overview'
export const OverviewUnionData = 'overviewUnionData'
export const OverviewCountNumListData = 'overviewCountNumListData'
export const OverviewExchangeData = 'overviewExchangeData'
export const OverviewRedListData = 'overviewRedListData'
export const OverviewBlackListData = 'overviewBlackListData'
export const OverviewClassStatisticData = 'overviewClassStatisticData'
export const OverviewTrendAnalysisData = 'overviewTrendAnalysisData'
export const OverviewSubmitDeptListData = 'overviewSubmitDeptListData'

export const Summary = 'summary'
export const SummaryMonthAnalysis = 'summaryMonthAnalysis'
export const SummaryClassifyStatistic = 'summaryClassifyStatistic'
export const SummaryCounts = 'summaryCounts'
export const SummarySource = 'summarySource'
export const SummaryNaturalPersonAnalysis = 'summaryNaturalPersonAnalysis'
export const SummaryNewestFillInDept = 'summaryNewestFillInDept'

export const Union = 'union'
export const Public = 'publicState'
export const Map = 'map'
