export const OverviewData = 'overviewData'
export const OverviewUnionData = 'overviewUnionData'
export const OverviewCountNumListData = 'overviewCountNumListData'
export const OverviewExchangeData = 'overviewExchangeData'
export const OverviewRedListData = 'overviewRedListData'
export const OverviewBlackListData = 'overviewBlackListData'
export const OverviewClassStatisticData = 'overviewClassStatisticData'
export const OverviewTrendAnalysisData = 'overviewTrendAnalysisData'
export const OverviewSubmitDeptListData = 'overviewSubmitDeptListData'

export const SummaryData = 'summaryData'
export const SummaryMonthAnalysis = 'summaryMonthAnalysis'
export const SummaryClassifyStatistic = 'summaryClassifyStatistic'
export const SummaryCounts = 'summaryCounts'
export const SummarySource = 'summarySource'
export const SummaryNaturalPersonAnalysis = 'summaryNaturalPersonAnalysis'
export const SummaryNewestFillInDept = 'summaryNewestFillInDept'

export const UnionData = 'unionData'
export const PublicData = 'publicData'
export const AffairData = 'affairData'
